import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";

const BUNDLE = "supabase/functions/mcp/index.ts";
const GENERATED_BANNER =
  "// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.\n" +
  "// To take ownership, delete this banner line; the plugin then leaves the file alone.";

describe("MCP generated Edge bundle stays generator-owned", () => {
  const source = readFileSync(BUNDLE, "utf8").replace(/\r\n/g, "\n");
  const installed = JSON.parse(
    readFileSync("node_modules/@lovable.dev/mcp-js/package.json", "utf8"),
  ).version as string;

  it("keeps the official AUTO-GENERATED ownership banner", () => {
    expect(source.startsWith(GENERATED_BANNER)).toBe(true);
  });

  it("does not contain an unauthorized manual-ownership banner", () => {
    expect(source.startsWith("// @ts-nocheck")).toBe(false);
    expect(source).not.toContain("ownership taken");
    expect(source).not.toContain("// @ts-nocheck — bundled output");
  });

  it("pins the installed mcp-js version", () => {
    expect(installed).toBe("0.20.0");
    const pins = [...source.matchAll(/@lovable\.dev\/mcp-js@([0-9]+\.[0-9]+\.[0-9]+)/g)].map((m) => m[1]);
    expect(pins.length).toBeGreaterThan(0);
    expect(new Set(pins)).toEqual(new Set([installed]));
  });

  it("is a Supabase Edge deployment artifact, not MCP source", () => {
    expect(source).toContain("Deno.serve(createSupabaseHandler(");
    expect(source).toContain('name: "get_market_movers"');
    expect(source).not.toContain("from \"@lovable.dev/mcp-js\"");
    expect(source).toContain("npm:@lovable.dev/mcp-js@");
    expect(source).not.toMatch(/import mcp from "npm:[A-Za-z]:[\\/]/);
  });
});
