project_id = "zcjptaolpumhtlwhlemq"

[functions.market-data]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.sync-stocks]
verify_jwt = false