project_id = "zcjptaolpumhtlwhlemq"

[functions.market-data]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.sync-stocks]
verify_jwt = false

[functions.sync-indexes]
verify_jwt = false

[functions.sync-screener-stocks]
verify_jwt = false

[functions.backfill-sectors]
verify_jwt = false

[functions.sync-news]
verify_jwt = false

[functions.sync-ipo-news]
verify_jwt = false

[functions.sync-ticker-search]
verify_jwt = false

[functions.get-watchlist-data]
verify_jwt = false

[functions.sync-historical-ipos]
verify_jwt = false

[functions.sync-market-caps]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.refresh-market-data]
verify_jwt = true

[functions.generate-daily-brief]
verify_jwt = false