export interface ReportTemplate {
  id: string;
  titleEn: string;
  titleEs: string;
}

export const REPORT_TEMPLATES: ReportTemplate[] = [
  { id: "daily-performance", titleEn: "Daily Performance", titleEs: "Rendimiento diario" },
  { id: "weekly-scorecard", titleEn: "Weekly Trader Scorecard", titleEs: "Tarjeta semanal del trader" },
  { id: "monthly-review", titleEn: "Monthly and Quarterly Review", titleEs: "Revisión mensual y trimestral" },
  { id: "equity-gross-net", titleEn: "Equity, Gross-to-Net and Realized/Unrealized", titleEs: "Patrimonio, bruto a neto y realizado/no realizado" },
  { id: "drawdown-recovery", titleEn: "Drawdown and Recovery", titleEs: "Drawdown y recuperación" },
  { id: "pnl-calendar", titleEn: "P&L Calendar", titleEs: "Calendario de P&L" },
  { id: "risk-utilization", titleEn: "Risk Utilization", titleEs: "Utilización de riesgo" },
  { id: "planned-vs-actual", titleEn: "Planned versus Actual Risk", titleEs: "Riesgo planificado versus real" },
  { id: "daily-loss-usage", titleEn: "Daily Loss Usage", titleEs: "Uso de pérdida diaria" },
  { id: "position-outliers", titleEn: "Position Outliers", titleEs: "Valores atípicos" },
  { id: "stop-adherence", titleEn: "Stop Adherence", titleEs: "Adherencia al stop" },
  { id: "open-risk", titleEn: "Open Risk and Concentration", titleEs: "Riesgo abierto y concentración" },
  { id: "rule-compliance", titleEn: "Rule and Prop Compliance", titleEs: "Cumplimiento de reglas" },
  { id: "playbook-scorecard", titleEn: "Playbook Scorecard", titleEs: "Tarjeta de playbook" },
  { id: "a-plus-checklist", titleEn: "A+ Checklist", titleEs: "Lista A+" },
  { id: "setup-condition", titleEn: "Setup and Market Condition", titleEs: "Setup y condición de mercado" },
  { id: "entry-exit-efficiency", titleEn: "Entry/Exit Efficiency", titleEs: "Eficiencia de entrada/salida" },
  { id: "slippage", titleEn: "Slippage", titleEs: "Deslizamiento" },
  { id: "scale-in-out", titleEn: "Scale-In/Scale-Out", titleEs: "Escalar entrada/salida" },
  { id: "mfe-mae", titleEn: "MFE/MAE", titleEs: "MFE/MAE" },
  { id: "holding-duration", titleEn: "Holding Duration and Partial Exit", titleEs: "Duración y salida parcial" },
  { id: "time-of-day", titleEn: "Time of Day", titleEs: "Hora del día" },
  { id: "day-of-week", titleEn: "Day of Week", titleEs: "Día de la semana" },
  { id: "session", titleEn: "Session", titleEs: "Sesión" },
  { id: "weekend-crypto", titleEn: "Weekend Crypto", titleEs: "Cripto de fin de semana" },
  { id: "trade-number", titleEn: "Trade Number", titleEs: "Número de operación" },
  { id: "process-score", titleEn: "Process Score", titleEs: "Puntaje de proceso" },
  { id: "mistake-cost", titleEn: "Mistake Cost", titleEs: "Costo del error" },
  { id: "strength", titleEn: "Strength", titleEs: "Fortaleza" },
  { id: "revenge-sequence", titleEn: "Revenge Sequence", titleEs: "Secuencia de revancha" },
  { id: "post-loss-win", titleEn: "Post-Loss/Post-Win", titleEs: "Tras pérdida/ganancia" },
  { id: "review-commitment", titleEn: "Review and Commitment", titleEs: "Revisión y compromiso" },
  { id: "emotion-outcome", titleEn: "Emotion-to-Outcome", titleEs: "Emoción y resultado" },
  { id: "symbol", titleEn: "Symbol", titleEs: "Símbolo" },
  { id: "long-vs-short", titleEn: "Long versus Short", titleEs: "Largo versus corto" },
  { id: "discovery-source", titleEn: "Discovery Source", titleEs: "Fuente de descubrimiento" },
  { id: "catalyst", titleEn: "Catalyst", titleEs: "Catalizador" },
  { id: "account-venue", titleEn: "Account and Venue", titleEs: "Cuenta y venue" },
  { id: "options-strategy", titleEn: "Options Strategy", titleEs: "Estrategia de opciones" },
  { id: "crypto-pair", titleEn: "Crypto Pair", titleEs: "Par cripto" },
  { id: "cash-flow", titleEn: "Cash Flow", titleEs: "Flujo de efectivo" },
  { id: "fee-drag", titleEn: "Fee Drag", titleEs: "Arrastre de comisiones" },
  { id: "locate-borrow", titleEn: "Locate/Borrow", titleEs: "Localización/préstamo" },
  { id: "options-settlement", titleEn: "Options Settlement", titleEs: "Liquidación de opciones" },
  { id: "crypto-conversion", titleEn: "Crypto Conversion", titleEs: "Conversión cripto" },
  { id: "reconciliation", titleEn: "Reconciliation", titleEs: "Conciliación" },
  { id: "data-quality", titleEn: "Data Quality", titleEs: "Calidad de datos" },
];
