/**
 * Scanner field registry — presentation, education, and availability only.
 *
 * This is not a data source. Unavailable fields stay registered so the UI can
 * explain them without fabricating values. Radar discovery/ranking is unchanged.
 */

export type ScannerFieldFormat =
  | "text"
  | "price"
  | "percent"
  | "volume"
  | "multiplier"
  | "datetime"
  | "enum"
  | "rank";

export type ScannerFieldCategory =
  | "identity"
  | "price"
  | "volume"
  | "range"
  | "catalyst"
  | "radar"
  | "fundamentals"
  | "triggers"
  | "time";

/**
 * available         — currently populated from a truthful source when present
 * source-dependent  — present only when the active source actually supplies it
 * unavailable       — registered placeholder; never synthesize a value
 */
export type ScannerFieldAvailability = "available" | "source-dependent" | "unavailable";

export interface ScannerFieldDefinition {
  id: string;
  label: string;
  shortLabel: string;
  description: string;
  whyItMatters: string;
  example?: string;
  format: ScannerFieldFormat;
  category: ScannerFieldCategory;
  sortable: boolean;
  filterable: boolean;
  defaultVisible: boolean;
  mobileVisible: boolean;
  tooltipEnabled: boolean;
  availability: ScannerFieldAvailability;
  /** Human-readable origin when useful for honesty copy. */
  source?: string;
}

export const SCANNER_FIELDS: readonly ScannerFieldDefinition[] = [
  {
    id: "symbol",
    label: "Symbol",
    shortLabel: "Symbol",
    description: "The ticker identity for this row.",
    whyItMatters: "Every Radar handoff — chart, watchlist, catalyst, AI, and journal — keys off this symbol.",
    format: "text",
    category: "identity",
    sortable: true,
    filterable: false,
    defaultVisible: true,
    mobileVisible: true,
    tooltipEnabled: false,
    availability: "available",
  },
  {
    id: "price",
    label: "Price",
    shortLabel: "Last",
    description: "The latest last price supplied by the active market-data source.",
    whyItMatters: "Price is the entry reference traders use to size risk and apply a price-band lens.",
    format: "price",
    category: "price",
    sortable: true,
    filterable: true,
    defaultVisible: true,
    mobileVisible: true,
    tooltipEnabled: true,
    availability: "source-dependent",
  },
  {
    id: "move",
    label: "Move",
    shortLabel: "Move",
    description:
      "Session price change versus prior close when that percentage is actually persisted. This is not a short-window Radar move.",
    whyItMatters: "Traders watch session move to see how far a name has already run before they engage.",
    example: "A +12% session move means the last price is 12% above the prior regular-session close.",
    format: "percent",
    category: "price",
    sortable: true,
    filterable: false,
    defaultVisible: true,
    mobileVisible: true,
    tooltipEnabled: true,
    availability: "source-dependent",
    source: "Not persisted by Radar V2; shown as unavailable rather than a 15s/60s substitute.",
  },
  {
    id: "volume",
    label: "Volume",
    shortLabel: "Vol",
    description: "Volume is the number of shares traded during a defined period.",
    whyItMatters: "Higher volume generally indicates greater participation and liquidity.",
    format: "volume",
    category: "volume",
    sortable: true,
    filterable: false,
    defaultVisible: true,
    mobileVisible: true,
    tooltipEnabled: true,
    availability: "available",
  },
  {
    id: "prior_volume",
    label: "Prior Volume",
    shortLabel: "Prior",
    description: "Previous regular-session share volume, when the source persists it.",
    whyItMatters: "Prior-session volume is the denominator for a current-versus-prior volume comparison.",
    format: "volume",
    category: "volume",
    sortable: true,
    filterable: false,
    defaultVisible: true,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "source-dependent",
    source: "Not persisted by Radar V2.",
  },
  {
    id: "volume_ratio",
    label: "Vol / Prior",
    shortLabel: "Vol/Prior",
    description: "Compares current session volume with the previous regular-session volume.",
    whyItMatters: "A large multiple can flag unusual participation relative to the prior session.",
    example: "5× means current volume is five times the prior session volume.",
    format: "multiplier",
    category: "volume",
    sortable: true,
    filterable: false,
    defaultVisible: true,
    mobileVisible: true,
    tooltipEnabled: true,
    availability: "source-dependent",
    source: "Not persisted by Radar V2.",
  },
  {
    id: "day_range",
    label: "Day Range",
    shortLabel: "Range",
    description:
      "Shows the stock's low and high for the current trading session. The marker shows where the current price is trading inside that range.",
    whyItMatters:
      "A stock holding near its high may indicate stronger momentum, while a stock far below its high may have already faded.",
    example: "Low $2.00, High $5.00, Last $4.70 places the marker near the right side of the range.",
    format: "text",
    category: "range",
    sortable: false,
    filterable: false,
    defaultVisible: true,
    mobileVisible: true,
    tooltipEnabled: true,
    availability: "source-dependent",
  },
  {
    id: "hod_distance",
    label: "HOD Distance",
    shortLabel: "HOD",
    description: "Shows how far the current price is below the session High of Day.",
    whyItMatters: "Names still near the high of day can indicate continued demand; a large discount may mean the move already faded.",
    example: "2.0% means last price is 2% below the session high.",
    format: "percent",
    category: "range",
    sortable: true,
    filterable: false,
    defaultVisible: true,
    mobileVisible: true,
    tooltipEnabled: true,
    availability: "source-dependent",
  },
  {
    id: "catalyst",
    label: "Catalyst",
    shortLabel: "Catalyst",
    description: "Confirmed news or event context attached to the symbol, when enrichment finds one.",
    whyItMatters: "Volume without a reason is harder to trade; a confirmed catalyst can explain why a name is active.",
    format: "text",
    category: "catalyst",
    sortable: false,
    filterable: false,
    defaultVisible: true,
    mobileVisible: true,
    tooltipEnabled: true,
    availability: "source-dependent",
  },
  {
    id: "data_time",
    label: "Data Time",
    shortLabel: "Data Time",
    description:
      "The provider timestamp associated with the latest market data for this row. This is NOT the time the breakout first occurred.",
    whyItMatters: "Data Time tells you how old the quote/tape evidence is. It must not be read as Trigger Time, surge time, or catalyst time.",
    format: "datetime",
    category: "time",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "available",
    source: "provider_as_of",
  },
  {
    id: "volume_5s",
    label: "5s Volume",
    shortLabel: "5s Vol",
    description: "Share volume accumulated over the most recent 5-second Radar window.",
    whyItMatters: "Very short-window volume can show whether participation is happening right now.",
    format: "volume",
    category: "radar",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "source-dependent",
    source: "Radar V2 rolling volume_5s",
  },
  {
    id: "volume_15s",
    label: "15s Volume",
    shortLabel: "15s Vol",
    description: "Share volume accumulated over the most recent 15-second Radar window.",
    whyItMatters: "A 15-second burst can distinguish a brief print from sustained participation.",
    format: "volume",
    category: "radar",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "source-dependent",
    source: "Radar V2 rolling volume_15s",
  },
  {
    id: "volume_60s",
    label: "60s Volume",
    shortLabel: "60s Vol",
    description: "Share volume accumulated over the most recent 60-second Radar window.",
    whyItMatters: "60-second volume is the primary short-window velocity reading Radar already persists.",
    format: "volume",
    category: "radar",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "source-dependent",
    source: "Radar V2 rolling volume_60s",
  },
  {
    id: "dollar_volume_60s",
    label: "60s Dollar Volume",
    shortLabel: "$ Vol 60s",
    description: "Approximate capital traded: share price × share volume.",
    whyItMatters: "Dollar volume shows whether size is actually transferring, not just share count.",
    example: "$10 last with 100,000 shares in 60 seconds is about $1.0M of 60s dollar volume.",
    format: "volume",
    category: "radar",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "source-dependent",
    source: "Radar V2 dollar_volume_60s / rolling_dollar_volume_60s",
  },
  {
    id: "acceleration_5m",
    label: "5m Acceleration",
    shortLabel: "5m Accel",
    description: "Shows whether trading activity is accelerating or slowing over the recent short-term window.",
    whyItMatters: "Rising acceleration can mark a name that is just getting going; fading acceleration can mark exhaustion.",
    format: "text",
    category: "radar",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "source-dependent",
    source: "Radar V2 acceleration_5m",
  },
  {
    id: "vwap_state",
    label: "VWAP State",
    shortLabel: "VWAP",
    description: "VWAP is the volume-weighted average price for the session.",
    whyItMatters: "Holding above VWAP can indicate buyers are in control; trading below can indicate sellers are in control.",
    format: "enum",
    category: "radar",
    sortable: false,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "source-dependent",
    source: "Radar V2 session_vwap + vwap_side",
  },
  {
    id: "freshness",
    label: "Freshness",
    shortLabel: "Fresh",
    description: "Radar's classification of how recently this candidate has printed meaningful activity.",
    whyItMatters: "Fresh names are still in play; stale names may already have cooled off.",
    format: "enum",
    category: "radar",
    sortable: false,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "source-dependent",
    source: "Radar V2 freshness_class",
  },
  {
    id: "move_15s",
    label: "15s Move",
    shortLabel: "15s Move",
    description: "Short-window percentage change over the last 15 seconds of Radar tape. This is not a day or session change.",
    whyItMatters: "A 15-second pop can flag an immediate burst without implying a full-day move.",
    format: "percent",
    category: "radar",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "source-dependent",
    source: "Radar V2 move_15s_pct",
  },
  {
    id: "move_60s",
    label: "60s Move",
    shortLabel: "60s Move",
    description: "Short-window percentage change over the last 60 seconds of Radar tape. This is not a day or session change.",
    whyItMatters: "A 60-second move is useful tape context and must never be labeled as Day Move.",
    format: "percent",
    category: "radar",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "source-dependent",
    source: "Radar V2 move_60s_pct",
  },
  {
    id: "float",
    label: "Float",
    shortLabel: "Float",
    description:
      "Stock float is the number of shares a company has available for the public to buy and sell on the open market.",
    whyItMatters:
      "Lower-float stocks can react more sharply when demand changes because fewer shares are available to trade.",
    example: "5M float with 25M shares traded equals approximately 5× float turnover.",
    format: "volume",
    category: "fundamentals",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
    source: "Not persisted by the current managed Screener / Radar V2 contract.",
  },
  {
    id: "float_turnover",
    label: "Float Turnover",
    shortLabel: "Turnover",
    description: "Current volume divided by shares in the public float.",
    whyItMatters: "High float turnover can mean the tradable supply has already changed hands several times in the session.",
    example: "5M float with 25M shares traded equals approximately 5× float turnover.",
    format: "multiplier",
    category: "fundamentals",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
  },
  {
    id: "short_float",
    label: "Short Float",
    shortLabel: "Short %",
    description: "The percentage of the public float that is currently sold short, when a verified source supplies it.",
    whyItMatters: "Elevated short float can add fuel if a squeezed short base is forced to cover.",
    format: "percent",
    category: "fundamentals",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
  },
  {
    id: "daily_rvol",
    label: "Daily RVOL",
    shortLabel: "RVOL",
    description: "Relative volume versus a typical full-day volume baseline.",
    whyItMatters: "Daily RVOL flags whether today's participation is unusual versus the stock's normal day.",
    format: "multiplier",
    category: "volume",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
    source: "Managed Screener contract currently requires rvol = null.",
  },
  {
    id: "rvol_5m",
    label: "5-minute RVOL",
    shortLabel: "5m RVOL",
    description: "Short-window relative volume / velocity versus a typical 5-minute baseline.",
    whyItMatters: "5-minute RVOL can show whether the current burst is unusual even if daily RVOL is not yet extreme.",
    format: "multiplier",
    category: "radar",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
  },
  {
    id: "spread",
    label: "Spread",
    shortLabel: "Spread",
    description: "The difference between the current bid and ask.",
    whyItMatters: "A wide spread is a hidden cost and can make entries and exits much worse than the last print.",
    format: "price",
    category: "price",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
  },
  {
    id: "market_cap",
    label: "Market Cap",
    shortLabel: "Mkt Cap",
    description: "The company's equity market value, when a verified source supplies it.",
    whyItMatters: "Market cap is a rough size filter; it is not a substitute for float.",
    format: "volume",
    category: "fundamentals",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
    source: "Managed Screener contract currently requires market_cap = null.",
  },
  {
    id: "ssr",
    label: "SSR",
    shortLabel: "SSR",
    description: "Short Sale Restriction status for the symbol, when a verified source supplies it.",
    whyItMatters: "SSR can change how easily a name is shorted during a down move.",
    format: "enum",
    category: "fundamentals",
    sortable: false,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
  },
  {
    id: "borrow_fee",
    label: "Borrow Fee",
    shortLabel: "Borrow",
    description: "The current stock-loan / hard-to-borrow fee, when a verified source supplies it.",
    whyItMatters: "An expensive borrow can squeeze shorts and also make shorting impractical.",
    format: "percent",
    category: "fundamentals",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
  },
  {
    id: "institutional_ownership",
    label: "Institutional Ownership",
    shortLabel: "Inst Own",
    description: "The percentage of shares held by institutions, when a verified source supplies it.",
    whyItMatters: "High institutional ownership can reduce tradable float even when reported float looks larger.",
    format: "percent",
    category: "fundamentals",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
  },
  {
    id: "trigger_time",
    label: "Trigger Time",
    shortLabel: "Trigger",
    description:
      "Future field: the time a breakout or trigger first occurred. This is not the provider data timestamp.",
    whyItMatters: "Traders need the event clock, not the last quote clock, to judge how late they are.",
    format: "datetime",
    category: "triggers",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
    source: "Architectural placeholder. Do not populate from provider_as_of.",
  },
  {
    id: "latest_trigger",
    label: "Latest Trigger",
    shortLabel: "Latest Trig",
    description: "Future field: the most recent trigger event on this symbol.",
    whyItMatters: "A fresh trigger is different from a name that triggered hours ago and is now cooling.",
    format: "text",
    category: "triggers",
    sortable: false,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
  },
  {
    id: "latest_trigger_time",
    label: "Latest Trigger Time",
    shortLabel: "Last Trig",
    description: "Future field: timestamp of the most recent trigger event. Not Data Time.",
    whyItMatters: "Latest trigger age tells you whether the setup is still live.",
    format: "datetime",
    category: "triggers",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
    source: "Architectural placeholder. Do not populate from provider_as_of.",
  },
  {
    id: "trigger_age",
    label: "Trigger Age",
    shortLabel: "Trig Age",
    description: "Future field: elapsed time since the relevant trigger event.",
    whyItMatters: "Age separates a just-triggered name from a leftover mover.",
    format: "text",
    category: "triggers",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
  },
  {
    id: "trigger_count",
    label: "Trigger Count",
    shortLabel: "Trig #",
    description: "Future field: how many verified trigger events have printed for this symbol in the session.",
    whyItMatters: "Repeated triggers can mean persistence; a single print may already be done.",
    format: "text",
    category: "triggers",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
  },
  {
    id: "trigger_type",
    label: "Trigger Type",
    shortLabel: "Trig Type",
    description: "Future field: classification of the trigger (for example a high-of-day hold or volume surge).",
    whyItMatters: "The kind of trigger changes how a trader should interpret the tape.",
    format: "enum",
    category: "triggers",
    sortable: false,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
  },
  {
    id: "catalyst_time",
    label: "Catalyst Time",
    shortLabel: "Cat Time",
    description: "Future field: timestamp of the catalyst event itself. Not Data Time and not Trigger Time.",
    whyItMatters: "Knowing when the news hit is different from knowing when the tape last updated.",
    format: "datetime",
    category: "triggers",
    sortable: true,
    filterable: false,
    defaultVisible: false,
    mobileVisible: false,
    tooltipEnabled: true,
    availability: "unavailable",
    source: "Architectural placeholder. Do not populate from provider_as_of.",
  },
] as const;

const FIELD_BY_ID: ReadonlyMap<string, ScannerFieldDefinition> = new Map(
  SCANNER_FIELDS.map((field) => [field.id, field]),
);

export function getScannerField(id: string): ScannerFieldDefinition | undefined {
  return FIELD_BY_ID.get(id);
}

export function scannerFieldIds(): string[] {
  return SCANNER_FIELDS.map((field) => field.id);
}

export function tooltipEnabledScannerFields(): ScannerFieldDefinition[] {
  return SCANNER_FIELDS.filter((field) => field.tooltipEnabled);
}
