/** Canonical public paths for sitemap type=main (no dashboard/auth/account). */
export const SITEMAP_MAIN_PAGES: ReadonlyArray<{
  path: string;
  pri: string;
  freq: string;
}> = [
  { path: "/", pri: "1.0", freq: "daily" },
  { path: "/about", pri: "0.6", freq: "monthly" },
  { path: "/contact", pri: "0.5", freq: "monthly" },
  { path: "/terms", pri: "0.3", freq: "yearly" },
  { path: "/privacy", pri: "0.3", freq: "yearly" },
  { path: "/disclaimer", pri: "0.3", freq: "yearly" },
  { path: "/faq", pri: "0.5", freq: "monthly" },
  { path: "/affiliates", pri: "0.4", freq: "monthly" },
  { path: "/methodology", pri: "0.4", freq: "monthly" },
  { path: "/pro", pri: "0.7", freq: "weekly" },
  { path: "/news", pri: "0.8", freq: "daily" },
  { path: "/trending", pri: "0.8", freq: "daily" },
  { path: "/screener", pri: "0.7", freq: "daily" },
  { path: "/earnings", pri: "0.7", freq: "daily" },
  { path: "/stocks", pri: "0.8", freq: "daily" },
  { path: "/chart", pri: "0.6", freq: "weekly" },
  { path: "/tools", pri: "0.6", freq: "monthly" },
  { path: "/newsletter", pri: "0.5", freq: "monthly" },
  { path: "/articles", pri: "0.7", freq: "daily" },
  { path: "/markets/gainers", pri: "0.7", freq: "daily" },
  { path: "/markets/losers", pri: "0.7", freq: "daily" },
  { path: "/markets/active", pri: "0.7", freq: "daily" },
  { path: "/markets/premarket", pri: "0.7", freq: "daily" },
  { path: "/markets/after-hours", pri: "0.7", freq: "daily" },
  { path: "/markets/heatmap", pri: "0.7", freq: "daily" },
  { path: "/ipos/recent", pri: "0.6", freq: "daily" },
  { path: "/ipos/calendar", pri: "0.6", freq: "daily" },
  { path: "/ipos/statistics", pri: "0.5", freq: "weekly" },
  { path: "/ipos/news", pri: "0.6", freq: "daily" },
  { path: "/etfs/screener", pri: "0.6", freq: "weekly" },
  { path: "/stocks/analysts", pri: "0.5", freq: "weekly" },
  { path: "/stocks/compare", pri: "0.6", freq: "weekly" },
  { path: "/stocks/lists", pri: "0.5", freq: "weekly" },
  { path: "/sitemap", pri: "0.3", freq: "monthly" },
];
