import { describe, it, expect } from "vitest";
import { execSync } from "node:child_process";
import { readFileSync } from "node:fs";

/**
 * The Pre-Market release must never touch the auto-generated MCP function.
 * Its `@lovable.dev/mcp-js` pin is owned by the installed package version and
 * regenerated by the Vite plugin — this guards against incidental drift.
 */
describe("MCP function file is untouched by Pre-Market work", () => {
  const path = "supabase/functions/mcp/index.ts";

  it("has no uncommitted diff", () => {
    const diff = execSync(`git diff -- ${path}`, { encoding: "utf8" });
    expect(diff).toBe("");
  });

  it("pins the installed mcp-js version everywhere", () => {
    const installed = JSON.parse(
      readFileSync("node_modules/@lovable.dev/mcp-js/package.json", "utf8"),
    ).version as string;
    const src = readFileSync(path, "utf8");
    const pins = [...src.matchAll(/@lovable\.dev\/mcp-js@([0-9]+\.[0-9]+\.[0-9]+)/g)].map((m) => m[1]);
    expect(pins.length).toBeGreaterThan(0);
    expect(new Set(pins)).toEqual(new Set([installed]));
  });
});
