// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-stocks.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var search_stocks_default = defineTool({
  name: "search_stocks",
  title: "Search stocks",
  description: "Search HedgeFun's stock database by ticker symbol or company name. Returns up to 20 matches with price, sector, and market cap.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Ticker symbol or company name fragment, e.g. 'AAPL' or 'apple'."),
    limit: z.number().int().min(1).max(20).optional().describe("Max results, default 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL ?? "",
      process.env.SUPABASE_PUBLISHABLE_KEY ?? "",
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const q = query.trim();
    const { data, error } = await supabase.from("stocks").select("symbol,name,price,change_percent,market_cap,sector,exchange").or(`symbol.ilike.${q}%,name.ilike.%${q}%`).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-stock-quote.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_stock_quote_default = defineTool2({
  name: "get_stock_quote",
  title: "Get stock quote",
  description: "Fetch the latest cached quote and fundamentals for a single ticker symbol from HedgeFun's stock database.",
  inputSchema: {
    symbol: z2.string().trim().min(1).max(10).describe("Ticker symbol, e.g. 'AAPL'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ symbol }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL ?? "",
      process.env.SUPABASE_PUBLISHABLE_KEY ?? "",
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("stocks").select("*").ilike("symbol", symbol.trim()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No quote found for ${symbol}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { quote: data }
    };
  }
});

// src/lib/mcp/tools/get-market-movers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";

// src/lib/quotes/integrity.ts
var TICKER_REGEX = /^[A-Z][A-Z0-9.-]{0,14}$/;
var USER_SNAPSHOT_UNAVAILABLE = "Current market snapshot unavailable";
var REASON_USER_TEXT = {
  MISSING_SYMBOL: USER_SNAPSHOT_UNAVAILABLE,
  MISSING_QUOTE: "Market snapshot unavailable.",
  MALFORMED_PRICE: USER_SNAPSHOT_UNAVAILABLE,
  NON_POSITIVE_PRICE: USER_SNAPSHOT_UNAVAILABLE,
  MALFORMED_CHANGE_PCT: USER_SNAPSHOT_UNAVAILABLE,
  MALFORMED_VOLUME: USER_SNAPSHOT_UNAVAILABLE,
  MISSING_QUOTE_TIMESTAMP: USER_SNAPSHOT_UNAVAILABLE,
  DECIMAL_SCALE_MISMATCH: USER_SNAPSHOT_UNAVAILABLE,
  CURRENCY_MISMATCH: USER_SNAPSHOT_UNAVAILABLE,
  SPLIT_ADJUSTMENT_MISMATCH: USER_SNAPSHOT_UNAVAILABLE,
  IMPLAUSIBLE_DISCONTINUITY: USER_SNAPSHOT_UNAVAILABLE
};
var CODE_USER_TEXT = {
  SNAPSHOT_MISSING: "Market snapshot unavailable.",
  SNAPSHOT_STALE: "Market snapshot is stale.",
  SNAPSHOT_MALFORMED: USER_SNAPSHOT_UNAVAILABLE,
  QUOTE_REJECTED: USER_SNAPSHOT_UNAVAILABLE,
  INSUFFICIENT_EVIDENCE: "Insufficient Data",
  PRICE_UNAVAILABLE: "Current price unavailable.",
  PRIOR_CLOSE_UNAVAILABLE: "Prior close unavailable.",
  BARS_MISSING: "Intraday bars unavailable.",
  BARS_INSUFFICIENT: "Not enough intraday bars for this session.",
  BARS_MALFORMED: "Intraday bar payload malformed.",
  VOLUME_UNAVAILABLE: "Volume unavailable.",
  PROVIDER_UNAVAILABLE: "Required upstream provider unavailable.",
  ...REASON_USER_TEXT
};
function normalizeSymbol(raw) {
  if (typeof raw !== "string") return null;
  const t = raw.trim().toUpperCase();
  return TICKER_REGEX.test(t) ? t : null;
}
function finiteOrNull(v) {
  if (typeof v === "number") return Number.isFinite(v) ? v : null;
  if (typeof v === "string" && v.trim() !== "") {
    const n = Number(v);
    return Number.isFinite(n) ? n : null;
  }
  return null;
}
function isMalformedNumber(v) {
  if (v === null || v === void 0) return false;
  if (typeof v === "number") return !Number.isFinite(v);
  if (typeof v === "string") {
    if (v.trim() === "") return false;
    return !Number.isFinite(Number(v));
  }
  return true;
}
function isoOrNull(v) {
  if (typeof v === "number" && Number.isFinite(v) && v > 0) {
    const ms = v > 1e14 ? Math.round(v / 1e6) : v;
    if (!Number.isFinite(ms) || ms < 1e12) return null;
    return new Date(ms).toISOString();
  }
  if (typeof v !== "string" || !v.trim()) return null;
  const t = Date.parse(v);
  return Number.isFinite(t) ? new Date(t).toISOString() : null;
}
var USD_ALIASES = /* @__PURE__ */ new Set([
  "USD",
  "US DOLLAR",
  "UNITED STATES DOLLAR",
  "UNITED STATES DOLLARS"
]);
function normalizeCurrency(raw) {
  if (typeof raw !== "string" || !raw.trim()) return null;
  return raw.trim().toUpperCase().replace(/[._]/g, " ").replace(/\s+/g, " ");
}
function isUsdCurrency(raw) {
  const c = normalizeCurrency(raw);
  return c !== null && USD_ALIASES.has(c);
}
var SCALE_FACTORS = [10, 100, 1e3];
var SPLIT_FACTORS = [2, 3, 4, 5, 10, 20, 25, 40, 50, 100];
var SCALE_TOLERANCE = 0.03;
function nearFactor(ratio, factor, tolerance = SCALE_TOLERANCE) {
  if (!Number.isFinite(ratio) || ratio <= 0) return false;
  return Math.abs(ratio - factor) / factor <= tolerance;
}
function pairRatio(a, b) {
  if (!(a > 0) || !(b > 0)) return null;
  return Math.max(a, b) / Math.min(a, b);
}
function isDecimalScalePair(a, b) {
  const ratio = pairRatio(a, b);
  if (ratio === null) return false;
  return SCALE_FACTORS.some((f) => nearFactor(ratio, f));
}
function isSplitFactorPair(a, b) {
  const ratio = pairRatio(a, b);
  if (ratio === null) return false;
  return SPLIT_FACTORS.some((f) => nearFactor(ratio, f));
}
function fail(input, opts, reason, field) {
  return {
    valid: false,
    rejection_reason: reason,
    rejected_field: field,
    symbol: opts.symbol,
    price: null,
    change_pct: null,
    volume: null,
    quote_timestamp: opts.ts,
    currency: opts.currency,
    raw: rawBundle(input),
    diagnostic: {
      symbol: opts.symbol,
      provider: opts.provider,
      quote_timestamp: opts.ts,
      rejected_field: field,
      reason
    }
  };
}
function rawBundle(input) {
  return {
    price: input.price ?? null,
    change_pct: input.changePct ?? null,
    volume: input.volume ?? null,
    last_trade: input.lastTradePrice ?? null,
    minute_close: input.minuteClose ?? null,
    day_close: input.dayClose ?? null,
    vwap: input.vwap ?? null,
    prior_close: input.priorClose ?? null
  };
}
function contemporaneousPrices(input) {
  const out = [];
  const push = (field, raw) => {
    const n = finiteOrNull(raw);
    if (n !== null && n > 0) out.push({ field, value: n });
  };
  push("price", input.price);
  push("lastTradePrice", input.lastTradePrice);
  push("minuteClose", input.minuteClose);
  push("dayClose", input.dayClose);
  push("vwap", input.vwap);
  return out;
}
function validateQuote(input, opts) {
  const provider = opts?.provider ?? "polygon";
  const symbol = normalizeSymbol(input.symbol);
  const ts = isoOrNull(input.quoteTimestamp);
  const currency = normalizeCurrency(input.currency);
  const ctx = { provider, symbol, ts, currency };
  if (!symbol) return fail(input, ctx, "MISSING_SYMBOL", "symbol");
  if (isMalformedNumber(input.price)) {
    return fail(input, ctx, "MALFORMED_PRICE", "price");
  }
  for (const [field, raw] of [
    ["lastTradePrice", input.lastTradePrice],
    ["minuteClose", input.minuteClose],
    ["dayClose", input.dayClose],
    ["vwap", input.vwap],
    ["priorClose", input.priorClose]
  ]) {
    if (isMalformedNumber(raw)) return fail(input, ctx, "MALFORMED_PRICE", field);
  }
  if (input.changePct !== void 0 && isMalformedNumber(input.changePct)) {
    return fail(input, ctx, "MALFORMED_CHANGE_PCT", "changePct");
  }
  if (input.volume !== void 0 && isMalformedNumber(input.volume)) {
    return fail(input, ctx, "MALFORMED_VOLUME", "volume");
  }
  const price = finiteOrNull(input.price);
  const lastTrade = finiteOrNull(input.lastTradePrice);
  const minuteClose = finiteOrNull(input.minuteClose);
  const dayClose = finiteOrNull(input.dayClose);
  const vwap = finiteOrNull(input.vwap);
  const priorClose = finiteOrNull(input.priorClose);
  const anyPrice = price !== null && price > 0 || lastTrade !== null && lastTrade > 0 || minuteClose !== null && minuteClose > 0 || dayClose !== null && dayClose > 0;
  if (!anyPrice) {
    const anyPresent = input.price !== void 0 && input.price !== null || input.lastTradePrice !== void 0 && input.lastTradePrice !== null || input.minuteClose !== void 0 && input.minuteClose !== null || input.dayClose !== void 0 && input.dayClose !== null;
    if (anyPresent) return fail(input, ctx, "NON_POSITIVE_PRICE", "price");
    return fail(input, ctx, "MISSING_QUOTE", "price");
  }
  const resolved = (price !== null && price > 0 ? price : null) ?? (lastTrade !== null && lastTrade > 0 ? lastTrade : null) ?? (minuteClose !== null && minuteClose > 0 ? minuteClose : null) ?? (dayClose !== null && dayClose > 0 ? dayClose : null);
  if (resolved === null || !(resolved > 0)) {
    return fail(input, ctx, "NON_POSITIVE_PRICE", "price");
  }
  if (currency && !isUsdCurrency(currency)) {
    return fail(input, ctx, "CURRENCY_MISMATCH", "currency");
  }
  const contemporaneous = contemporaneousPrices(input);
  for (let i = 0; i < contemporaneous.length; i++) {
    for (let j = i + 1; j < contemporaneous.length; j++) {
      const a = contemporaneous[i];
      const b = contemporaneous[j];
      if (a.value === b.value) continue;
      if (isDecimalScalePair(a.value, b.value)) {
        return fail(input, ctx, "DECIMAL_SCALE_MISMATCH", `${a.field}/${b.field}`);
      }
    }
  }
  const adjusted = finiteOrNull(input.adjustedClose);
  const unadjusted = finiteOrNull(input.unadjustedClose);
  if (adjusted !== null && adjusted > 0 && unadjusted !== null && unadjusted > 0) {
    if (isDecimalScalePair(adjusted, unadjusted) || isSplitFactorPair(adjusted, unadjusted)) {
      const ratio = pairRatio(adjusted, unadjusted);
      if (ratio !== null && ratio >= 1.8) {
        return fail(input, ctx, "SPLIT_ADJUSTMENT_MISMATCH", "adjustedClose/unadjustedClose");
      }
    }
  }
  const priorTrusted = finiteOrNull(input.priorSnapshotPrice);
  if (priorTrusted !== null && priorTrusted > 0) {
    const ratio = pairRatio(resolved, priorTrusted);
    if (ratio !== null && ratio >= 4 && !isSplitFactorPair(resolved, priorTrusted)) {
      return fail(input, ctx, "IMPLAUSIBLE_DISCONTINUITY", "priorSnapshotPrice");
    }
    if (ratio !== null && isDecimalScalePair(resolved, priorTrusted)) {
      return fail(input, ctx, "DECIMAL_SCALE_MISMATCH", "price/priorSnapshotPrice");
    }
  }
  const changePct = finiteOrNull(input.changePct);
  const volume = finiteOrNull(input.volume);
  if (volume !== null && volume < 0) {
    return fail(input, ctx, "MALFORMED_VOLUME", "volume");
  }
  return {
    valid: true,
    rejection_reason: null,
    rejected_field: null,
    symbol,
    price: resolved,
    change_pct: changePct,
    volume: volume !== null && volume >= 0 ? volume : null,
    quote_timestamp: ts,
    currency,
    raw: rawBundle(input),
    diagnostic: {
      symbol,
      provider,
      quote_timestamp: ts,
      rejected_field: null,
      reason: null
    }
  };
}
function isPlainObject(x) {
  return x !== null && typeof x === "object" && !Array.isArray(x);
}
function extractPolygonSnapshotFields(body, symbolHint) {
  if (!isPlainObject(body)) return null;
  const tick = isPlainObject(body.ticker) ? body.ticker : body;
  const prevDay = isPlainObject(tick.prevDay) ? tick.prevDay : {};
  const day = isPlainObject(tick.day) ? tick.day : {};
  const lastTrade = isPlainObject(tick.lastTrade) ? tick.lastTrade : {};
  const min = isPlainObject(tick.min) ? tick.min : {};
  const details = isPlainObject(tick.details) ? tick.details : {};
  const symbol = symbolHint ?? tick.ticker ?? (typeof body.ticker === "string" ? body.ticker : null);
  const currency = details.currency_symbol ?? details.currency_name ?? tick.currency ?? body.currency ?? null;
  const ts = lastTrade.t ?? tick.updated ?? min.t ?? null;
  const price = (typeof lastTrade.p === "number" && lastTrade.p > 0 ? lastTrade.p : null) ?? (typeof min.c === "number" && min.c > 0 ? min.c : null) ?? (typeof day.c === "number" && day.c > 0 ? day.c : null);
  return {
    symbol,
    price,
    lastTradePrice: lastTrade.p,
    minuteClose: min.c,
    dayClose: day.c,
    vwap: day.vw,
    priorClose: prevDay.c,
    quoteTimestamp: ts,
    volume: day.v,
    currency
  };
}

// src/lib/markets/movers-integrity.ts
var SOURCE_POLYGON = "polygon";
var SOURCE_MARKET_MOVERS_CACHE = "market_movers";
var SOURCE_AFTER_HOURS_FEED = "after_hours_feed";
var SOURCE_RANK = {
  [SOURCE_POLYGON]: 0,
  [SOURCE_AFTER_HOURS_FEED]: 1,
  [SOURCE_MARKET_MOVERS_CACHE]: 2
};
var SCALE_FACTORS2 = [10, 100, 1e3];
var SPLIT_FACTORS2 = [2, 3, 4, 5, 10, 20, 25, 40, 50, 100];
var SCALE_TOLERANCE2 = 0.03;
var PERCENT_ABS_TOLERANCE = 1;
var PERCENT_REL_TOLERANCE = 0.08;
var STALE_REFERENCE_MS = 18 * 60 * 60 * 1e3;
var RECAP_RATIO_FLOOR = 200;
function etSessionDate(ms = Date.now()) {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: "America/New_York",
    year: "numeric",
    month: "2-digit",
    day: "2-digit"
  }).formatToParts(new Date(ms));
  const year = parts.find((p) => p.type === "year")?.value;
  const month = parts.find((p) => p.type === "month")?.value;
  const day = parts.find((p) => p.type === "day")?.value;
  if (!year || !month || !day) return "";
  return `${year}-${month}-${day}`;
}
function canonicalChangePercent(currentPrice, referencePrice) {
  if (!(currentPrice > 0) || !(referencePrice > 0)) return null;
  const pct = (currentPrice - referencePrice) / referencePrice * 100;
  return Number.isFinite(pct) ? pct : null;
}
function nearFactor2(ratio, factor, tolerance = SCALE_TOLERANCE2) {
  if (!Number.isFinite(ratio) || ratio <= 0) return false;
  return Math.abs(ratio - factor) / factor <= tolerance;
}
function pairRatio2(a, b) {
  if (!(a > 0) || !(b > 0)) return null;
  return Math.max(a, b) / Math.min(a, b);
}
function isDecimalScalePair2(a, b) {
  const ratio = pairRatio2(a, b);
  if (ratio === null) return false;
  return SCALE_FACTORS2.some((f) => nearFactor2(ratio, f));
}
function isSplitFactorPair2(a, b) {
  const ratio = pairRatio2(a, b);
  if (ratio === null) return false;
  return SPLIT_FACTORS2.some((f) => nearFactor2(ratio, f));
}
function percentsAgree(a, b) {
  const abs = Math.abs(a - b);
  if (abs <= PERCENT_ABS_TOLERANCE) return true;
  const denom = Math.max(Math.abs(a), Math.abs(b), 1);
  return abs / denom <= PERCENT_REL_TOLERANCE;
}
function isRatioVersusPercent(provider, canonical) {
  if (!(Math.abs(provider) > 0) || !(Math.abs(canonical) > 0)) return false;
  if (Math.sign(provider) !== Math.sign(canonical) && provider !== 0 && canonical !== 0) {
    return false;
  }
  const ratio = Math.abs(canonical) / Math.abs(provider);
  return nearFactor2(ratio, 100) || nearFactor2(ratio, 0.01);
}
function nameFrom(raw, symbol) {
  if (typeof raw === "string" && raw.trim()) return raw.trim();
  return symbol;
}
function sourceFrom(raw) {
  if (typeof raw === "string" && raw.trim()) return raw.trim();
  return SOURCE_POLYGON;
}
function fail2(input, symbol, reason) {
  return {
    valid: false,
    reason,
    symbol,
    name: nameFrom(input.name, symbol ?? ""),
    price: null,
    reference_price: null,
    change: null,
    change_percent: null,
    volume: finiteOrNull(input.volume),
    session: input.session ?? null,
    session_date: typeof input.sessionDate === "string" ? input.sessionDate : null,
    source: sourceFrom(input.source),
    provider_as_of: isoOrNull(input.providerAsOf),
    id: typeof input.id === "string" ? input.id : null
  };
}
function validateMover(input) {
  const symbol = normalizeSymbol(input.symbol);
  if (!symbol) return fail2(input, null, "malformed_symbol");
  const extended = input.session === "premarket" || input.session === "afterhours";
  const quote = validateQuote({
    symbol,
    price: input.price,
    lastTradePrice: input.lastTradePrice,
    minuteClose: input.minuteClose,
    dayClose: extended ? void 0 : input.dayClose,
    vwap: extended ? void 0 : input.vwap,
    priorClose: input.referencePrice,
    volume: input.volume,
    quoteTimestamp: input.providerAsOf,
    adjustedClose: input.adjustedClose,
    unadjustedClose: input.unadjustedClose
  }, { provider: sourceFrom(input.source) });
  if (!quote.valid) {
    if (quote.rejection_reason === "DECIMAL_SCALE_MISMATCH") {
      return fail2(input, symbol, "decimal_scale_mismatch");
    }
    if (quote.rejection_reason === "SPLIT_ADJUSTMENT_MISMATCH") {
      return fail2(input, symbol, "adjustment_mismatch");
    }
    if (quote.rejection_reason === "MISSING_QUOTE" || quote.rejection_reason === "NON_POSITIVE_PRICE" || quote.rejection_reason === "MALFORMED_PRICE") {
      return fail2(input, symbol, "invalid_current_price");
    }
    return fail2(input, symbol, "invalid_current_price");
  }
  const current = finiteOrNull(input.price) ?? quote.price;
  if (current === null || !(current > 0)) {
    return fail2(input, symbol, "invalid_current_price");
  }
  if (input.referencePrice === void 0 || input.referencePrice === null) {
    return fail2(input, symbol, "missing_corroboration");
  }
  const reference = finiteOrNull(input.referencePrice);
  if (reference === null || !(reference > 0)) {
    return fail2(input, symbol, "invalid_reference_price");
  }
  if (isDecimalScalePair2(current, reference)) {
    return fail2(input, symbol, "decimal_scale_mismatch");
  }
  const recapRatio = pairRatio2(current, reference);
  if (recapRatio !== null && recapRatio >= RECAP_RATIO_FLOOR) {
    return fail2(input, symbol, "adjustment_mismatch");
  }
  const adjusted = finiteOrNull(input.adjustedClose);
  const unadjusted = finiteOrNull(input.unadjustedClose);
  if (adjusted !== null && adjusted > 0 && unadjusted !== null && unadjusted > 0) {
    if (isDecimalScalePair2(adjusted, unadjusted) || isSplitFactorPair2(adjusted, unadjusted)) {
      const ratio = pairRatio2(adjusted, unadjusted);
      if (ratio !== null && ratio >= 1.8) {
        return fail2(input, symbol, "adjustment_mismatch");
      }
    }
  }
  const canonicalPct = canonicalChangePercent(current, reference);
  if (canonicalPct === null) return fail2(input, symbol, "invalid_reference_price");
  const providerPct = finiteOrNull(input.providerPercent);
  if (providerPct !== null && isRatioVersusPercent(providerPct, canonicalPct) && !percentsAgree(providerPct, canonicalPct)) {
    return fail2(input, symbol, "percentage_mismatch");
  }
  const nowMs = typeof input.nowMs === "number" && Number.isFinite(input.nowMs) ? input.nowMs : Date.now();
  const asOf = isoOrNull(input.providerAsOf);
  if (asOf) {
    const asOfMs = Date.parse(asOf);
    if (Number.isFinite(asOfMs) && nowMs - asOfMs > STALE_REFERENCE_MS) {
      return fail2(input, symbol, "stale_reference");
    }
  }
  const sessionDate = typeof input.sessionDate === "string" && /^\d{4}-\d{2}-\d{2}$/.test(input.sessionDate) ? input.sessionDate : null;
  if (sessionDate && sessionDate !== etSessionDate(nowMs) && input.source === SOURCE_MARKET_MOVERS_CACHE) {
    return fail2(input, symbol, "stale_reference");
  }
  const volume = finiteOrNull(input.volume);
  return {
    valid: true,
    reason: null,
    symbol,
    name: nameFrom(input.name, symbol),
    price: current,
    reference_price: reference,
    change: current - reference,
    change_percent: canonicalPct,
    volume: volume !== null && volume >= 0 ? volume : null,
    session: input.session ?? null,
    session_date: sessionDate,
    source: sourceFrom(input.source),
    provider_as_of: asOf,
    id: typeof input.id === "string" ? input.id : null
  };
}
function isPlainObject2(x) {
  return x !== null && typeof x === "object" && !Array.isArray(x);
}
function moverFromExtendedObservation(input, nowMs = Date.now()) {
  return validateMover({
    symbol: input.symbol,
    name: input.name,
    price: input.extendedLast,
    referencePrice: input.regularClose,
    providerPercent: input.changePercent,
    lastTradePrice: input.extendedLast,
    minuteClose: input.extendedLast,
    volume: input.volume,
    providerAsOf: input.providerAsOf,
    session: "afterhours",
    sessionDate: etSessionDate(nowMs),
    source: input.source ?? SOURCE_AFTER_HOURS_FEED,
    id: input.id,
    nowMs
  });
}
function polygonTickersFromResponse(res) {
  if (Array.isArray(res)) return res;
  if (isPlainObject2(res) && Array.isArray(res.tickers)) return res.tickers;
  return [];
}
function moverFromPolygonTicker(raw, session, nowMs = Date.now()) {
  if (!isPlainObject2(raw)) {
    return fail2({ symbol: null }, null, "malformed_symbol");
  }
  const extracted = extractPolygonSnapshotFields(raw, raw.ticker ?? raw.symbol);
  const lastTrade = isPlainObject2(raw.lastTrade) ? raw.lastTrade : {};
  const min = isPlainObject2(raw.min) ? raw.min : {};
  const day = isPlainObject2(raw.day) ? raw.day : {};
  const prevDay = isPlainObject2(raw.prevDay) ? raw.prevDay : {};
  const lastTradePrice = finiteOrNull(lastTrade.p);
  const minuteClose = finiteOrNull(min.c);
  const dayClose = finiteOrNull(day.c);
  const prevClose = finiteOrNull(prevDay.c);
  let current = null;
  let reference = null;
  if (session === "regular") {
    current = dayClose;
    reference = prevClose;
  } else if (session === "premarket") {
    current = (lastTradePrice !== null && lastTradePrice > 0 ? lastTradePrice : null) ?? (minuteClose !== null && minuteClose > 0 ? minuteClose : null);
    reference = prevClose;
  } else {
    current = (lastTradePrice !== null && lastTradePrice > 0 ? lastTradePrice : null) ?? (minuteClose !== null && minuteClose > 0 ? minuteClose : null);
    reference = dayClose;
  }
  const providerPct = finiteOrNull(raw.todaysChangePerc ?? raw.change_percent ?? raw.changePercent);
  const sessionDate = etSessionDate(nowMs);
  if (session === "regular" && dayClose !== null && dayClose > 0 && current === dayClose && providerPct !== null && prevClose !== null && prevClose > 0) {
    const dayPct = canonicalChangePercent(dayClose, prevClose);
    const extPrice = (lastTradePrice !== null && lastTradePrice > 0 ? lastTradePrice : null) ?? (minuteClose !== null && minuteClose > 0 ? minuteClose : null);
    if (extPrice !== null && dayPct !== null) {
      const extPct = canonicalChangePercent(extPrice, prevClose);
      if (extPct !== null && !percentsAgree(providerPct, dayPct) && percentsAgree(providerPct, extPct) && !percentsAgree(extPct, dayPct)) {
        return fail2({
          symbol: extracted?.symbol ?? raw.ticker ?? raw.symbol,
          name: raw.name,
          session,
          sessionDate,
          source: SOURCE_POLYGON,
          providerAsOf: extracted?.quoteTimestamp ?? lastTrade.t ?? raw.updated
        }, normalizeSymbol(extracted?.symbol ?? raw.ticker ?? raw.symbol), "session_mismatch");
      }
    }
  }
  return validateMover({
    symbol: extracted?.symbol ?? raw.ticker ?? raw.symbol,
    name: raw.name ?? (isPlainObject2(raw.details) ? raw.details.name : null),
    price: current,
    referencePrice: reference,
    providerPercent: providerPct,
    lastTradePrice,
    minuteClose,
    dayClose,
    vwap: extracted?.vwap,
    volume: finiteOrNull(day.v) ?? finiteOrNull(min.av) ?? finiteOrNull(min.v),
    providerAsOf: extracted?.quoteTimestamp ?? lastTrade.t ?? raw.updated,
    session,
    sessionDate,
    source: SOURCE_POLYGON,
    nowMs
  });
}
function toMoverListRow(mover) {
  if (!mover.valid || !mover.symbol || mover.price === null || mover.change === null || mover.change_percent === null) {
    return null;
  }
  return {
    symbol: mover.symbol,
    name: mover.name,
    price: mover.price,
    change: mover.change,
    changePercent: mover.change_percent,
    volume: mover.volume !== null && mover.volume >= 0 ? mover.volume : 0
  };
}
function eventTimeMs(iso) {
  if (!iso) return 0;
  const t = Date.parse(iso);
  return Number.isFinite(t) ? t : 0;
}
function sourceRank(source) {
  return SOURCE_RANK[source] ?? 50;
}
function currentMoverIdentity(row) {
  if (!row.symbol) return null;
  const session = row.session ?? "_";
  const date = row.session_date ?? "_";
  return `${row.symbol}|${session}|${date}`;
}
function compareWinners(a, b) {
  if (a.valid !== b.valid) return a.valid ? -1 : 1;
  const dt = eventTimeMs(b.provider_as_of) - eventTimeMs(a.provider_as_of);
  if (dt !== 0) return dt;
  const src = sourceRank(a.source) - sourceRank(b.source);
  if (src !== 0) return src;
  const va = a.volume ?? -1;
  const vb = b.volume ?? -1;
  if (va !== vb) return vb - va;
  const ida = a.id ?? a.symbol ?? "";
  const idb = b.id ?? b.symbol ?? "";
  return ida.localeCompare(idb);
}
function selectCanonicalCurrentMovers(rows, opts) {
  const sessionDate = opts?.sessionDate;
  const eligible = rows.filter((r) => {
    if (!r.valid) return false;
    if (sessionDate && r.session_date && r.session_date !== sessionDate) return false;
    return true;
  });
  const ranked = [...eligible].sort(compareWinners);
  const seen = /* @__PURE__ */ new Set();
  const winners = [];
  for (const row of ranked) {
    const key = currentMoverIdentity(row);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    winners.push(row);
  }
  const sort = opts?.sort ?? "percent_desc";
  winners.sort((a, b) => {
    if (sort === "volume_desc") {
      const dv = (b.volume ?? 0) - (a.volume ?? 0);
      if (dv !== 0) return dv;
    } else {
      const pa = a.change_percent ?? 0;
      const pb = b.change_percent ?? 0;
      const dp = sort === "percent_asc" ? pa - pb : pb - pa;
      if (dp !== 0) return dp;
    }
    return compareWinners(a, b);
  });
  return winners;
}
function mapPolygonMovers(raw, session, opts) {
  const nowMs = opts?.nowMs ?? Date.now();
  const tickers = polygonTickersFromResponse(raw);
  const validated = tickers.map((t) => moverFromPolygonTicker(t, session, nowMs));
  const winners = selectCanonicalCurrentMovers(validated, {
    sessionDate: etSessionDate(nowMs),
    sort: opts?.sort
  });
  const rows = winners.map(toMoverListRow).filter((r) => r !== null);
  return { rows, rejected: validated.length - winners.length };
}
function presentCanonicalMovers(movers, category, limit = 10, nowMs = Date.now()) {
  let sort = "percent_desc";
  if (category === "loser") sort = "percent_asc";
  if (category === "active") sort = "volume_desc";
  let filtered = movers;
  if (category === "gainer") filtered = movers.filter((m) => (m.change_percent ?? 0) > 0);
  if (category === "loser") filtered = movers.filter((m) => (m.change_percent ?? 0) < 0);
  const winners = selectCanonicalCurrentMovers(filtered, {
    sessionDate: etSessionDate(nowMs),
    sort
  });
  const rows = winners.slice(0, Math.max(1, limit)).filter((m) => m.symbol && m.price !== null && m.change_percent !== null).map((m) => ({
    symbol: m.symbol,
    name: m.name,
    price: m.price,
    change_percent: m.change_percent,
    volume: m.volume,
    session_date: m.session_date
  }));
  return { movers: rows, status: rows.length > 0 ? "available" : "empty" };
}

// src/lib/mcp/tools/get-market-movers.ts
async function fetchMarketDataTickers(kind, env) {
  if (!env.url || !env.key) return [];
  const url = `${env.url.replace(/\/$/, "")}/functions/v1/market-data?type=${kind}`;
  const res = await fetch(url, {
    headers: {
      Authorization: `Bearer ${env.key}`,
      apikey: env.key
    }
  });
  if (!res.ok) return [];
  return res.json();
}
function sessionForCategory(category) {
  if (category === "premarket") return "premarket";
  if (category === "afterhours") return "afterhours";
  return "regular";
}
function canonicalizeLiveTickers(payload, category, nowMs = Date.now()) {
  const session = sessionForCategory(category);
  const tickers = Array.isArray(payload) ? payload : payload && typeof payload === "object" && Array.isArray(payload.tickers) ? payload.tickers : [];
  return tickers.map((t) => moverFromPolygonTicker(t, session, nowMs));
}
function presentValidatedMovers(movers, category, limit, nowMs = Date.now()) {
  return presentCanonicalMovers(movers, category, limit, nowMs);
}
var get_market_movers_default = defineTool3({
  name: "get_market_movers",
  title: "Get market movers",
  description: "List today's top market movers (gainers, losers, most active, pre-market, or after-hours) from HedgeFun's data.",
  inputSchema: {
    type: z3.enum(["gainer", "loser", "active", "premarket", "afterhours"]).describe("Which mover category to return."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max results, default 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type, limit }) => {
    const env = {
      url: process.env.SUPABASE_URL ?? "",
      key: process.env.SUPABASE_PUBLISHABLE_KEY ?? ""
    };
    const supabase = createClient3(env.url, env.key, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const cap = limit ?? 10;
    const nowMs = Date.now();
    if (type === "afterhours") {
      const [{ data: stateRows }, { data: resultRows, error }] = await Promise.all([
        supabase.from("after_hours_feed_state").select("state_key,generation_id,status,session_date,synced_at").eq("state_key", "current").limit(1),
        supabase.from("after_hours_mover_results").select("generation_id,side,rank,symbol,company_name,extended_last,regular_close,change_percent,volume,provider_as_of")
      ]);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      const state = (stateRows ?? [])[0];
      const gen = typeof state?.generation_id === "string" ? state.generation_id : null;
      const validated2 = (resultRows ?? []).filter((r) => gen && r.generation_id === gen).map(
        (r) => moverFromExtendedObservation({
          symbol: r.symbol,
          name: r.company_name,
          extendedLast: r.extended_last,
          regularClose: r.regular_close,
          volume: r.volume,
          providerAsOf: r.provider_as_of,
          changePercent: r.change_percent,
          source: SOURCE_AFTER_HOURS_FEED
        }, nowMs)
      );
      const presented2 = presentValidatedMovers(validated2, "afterhours", cap, nowMs);
      return {
        content: [{ type: "text", text: JSON.stringify(presented2.movers) }],
        structuredContent: { movers: presented2.movers, status: presented2.status }
      };
    }
    const kinds = type === "loser" ? ["losers"] : type === "gainer" ? ["gainers"] : ["gainers", "losers"];
    const payloads = await Promise.all(kinds.map((k) => fetchMarketDataTickers(k, env)));
    const validated = payloads.flatMap((p) => canonicalizeLiveTickers(p, type, nowMs));
    if (type === "active") {
      const { rows } = mapPolygonMovers(
        payloads.flatMap((p) => polygonTickersFromResponse(p)),
        "regular",
        { nowMs, sort: "volume_desc" }
      );
      const movers = rows.slice(0, cap).map((r) => ({
        symbol: r.symbol,
        name: r.name,
        price: r.price,
        change_percent: r.changePercent,
        volume: r.volume,
        session_date: etSessionDate(nowMs)
      }));
      return {
        content: [{ type: "text", text: JSON.stringify(movers) }],
        structuredContent: { movers, status: movers.length > 0 ? "available" : "empty" }
      };
    }
    const presented = presentValidatedMovers(validated, type, cap, nowMs);
    return {
      content: [{ type: "text", text: JSON.stringify(presented.movers) }],
      structuredContent: { movers: presented.movers, status: presented.status }
    };
  }
});

// src/lib/mcp/tools/get-market-news.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var get_market_news_default = defineTool4({
  name: "get_market_news",
  title: "Get market news",
  description: "Return the most recent market news headlines from HedgeFun, optionally filtered by category.",
  inputSchema: {
    category: z4.enum(["markets", "stocks", "ipo", "etf", "general"]).optional().describe("Optional news category filter."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max headlines, default 15.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL ?? "",
      process.env.SUPABASE_PUBLISHABLE_KEY ?? "",
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("market_news").select("headline,source,url,category,published_at").order("published_at", { ascending: false }).limit(limit ?? 15);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { news: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zcjptaolpumhtlwhlemq";
var mcp_default = defineMcp({
  name: "hedgefun-mcp",
  title: "HedgeFun Market Data",
  version: "0.1.0",
  instructions: "Tools for HedgeFun stock market data. Use `search_stocks` to find tickers by name or symbol, `get_stock_quote` for a single ticker's latest cached quote and fundamentals, `get_market_movers` for today's top gainers/losers/most-active/pre-market/after-hours lists, and `get_market_news` for recent market headlines. All data is cached market data; sign in with your HedgeFun account to connect.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_stocks_default, get_stock_quote_default, get_market_movers_default, get_market_news_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
