import { useEffect } from "react";
import { AdBanner } from "@/components/layout/AdBanner";

export default function AffiliatesPage() {
  useEffect(() => {
    document.title = "Affiliate & Editorial Disclosure | Stocksist";
  }, []);

  return (
    <>
      <div className="max-w-[800px] mx-auto px-6 py-12">
        <h1 className="text-[1.75rem] font-bold text-foreground border-b-2 border-border pb-3 mb-4">
          Affiliate & Editorial Disclosure
        </h1>
        <p className="text-xs text-muted-foreground mb-6">
          Last updated: April 8, 2026
        </p>

        <div className="text-base leading-[1.8] text-foreground space-y-6">
          <section>
            <h2 className="text-[1.125rem] font-bold mb-2">Overview</h2>
            <p>
              Stocksist ("stocksist.com," "we," "us," or "our") is committed to full transparency regarding how our platform is funded. This page discloses all material relationships that may influence the content displayed on our website in accordance with the Federal Trade Commission (FTC) Endorsement Guides (16 CFR Part 255) and Google AdSense Program Policies.
            </p>
          </section>

          <section>
            <h2 className="text-[1.125rem] font-bold mb-2">Advertising Revenue</h2>
            <p>
              Stocksist displays advertisements provided by <strong>Google AdSense</strong>, a third-party advertising network operated by Google LLC. These advertisements are served automatically based on page content and user browsing behavior using cookies (including the DoubleClick DART cookie). Stocksist earns revenue when users view or interact with these advertisements. The placement, content, and targeting of Google AdSense advertisements are determined by Google's algorithms, not by Stocksist's editorial team.
            </p>
            <p className="mt-2">
              You may opt out of personalized advertising by visiting{" "}
              <a href="https://www.google.com/settings/ads" target="_blank" rel="noopener noreferrer" className="text-accent-blue hover:underline">
                Google's Ads Settings
              </a>{" "}
              or the{" "}
              <a href="https://optout.networkadvertising.org/" target="_blank" rel="noopener noreferrer" className="text-accent-blue hover:underline">
                Network Advertising Initiative opt-out page
              </a>.
            </p>
          </section>

          <section>
            <h2 className="text-[1.125rem] font-bold mb-2">Broker & Financial Affiliate Programs</h2>
            <p>
              Stocksist may participate in affiliate programs offered by registered broker-dealers, financial data providers, and fintech platforms. When you click an affiliate link on our site and subsequently open an account, fund a brokerage account, or purchase a subscription through a partner service, Stocksist may receive a referral commission at no additional cost to you.
            </p>
            <p className="mt-2">
              Potential affiliate relationships may include, but are not limited to, online brokerages, options trading platforms, charting software providers, and financial education services. All affiliate links on Stocksist are clearly identified. The existence of an affiliate relationship does not constitute an endorsement, recommendation, or solicitation to buy or sell any security.
            </p>
          </section>

          <section>
            <h2 className="text-[1.125rem] font-bold mb-2">Editorial Independence & AI Integrity</h2>
            <p>
              <strong>Financial compensation from advertising or affiliate partnerships does NOT influence the algorithmic analysis, stock screener results, Socratic AI questioning, or any data-driven output generated by the Stocksist platform.</strong>
            </p>
            <p className="mt-2">
              Our AI-powered analysis tools, including the Stocksist AI, operate on objective, quantitative methodologies derived from publicly available market data sourced from third-party APIs (such as Polygon.io). The algorithms powering our screeners, earnings calendars, options flow analysis, and credit spread evaluations are designed and maintained independently of any advertising or affiliate revenue stream. No advertiser, affiliate partner, or sponsor has the ability to alter, suppress, or influence the output of our data models or AI agents.
            </p>
            <p className="mt-2">
              Editorial content, including market commentary, educational articles, and tool descriptions, is produced by the Stocksist team and reviewed for accuracy. Sponsored content, if any, will always be clearly labeled as such.
            </p>
          </section>

          <section>
            <h2 className="text-[1.125rem] font-bold mb-2">Stocksist Pro Subscriptions</h2>
            <p>
              Stocksist Pro is our premium subscription service. Revenue from Pro subscriptions directly funds platform development, server infrastructure, and data licensing costs. Stocksist Pro features (such as extended financial history, advanced screener filters, and analyst ratings) are determined by product utility, not by affiliate or advertising interests.
            </p>
          </section>

          <section>
            <h2 className="text-[1.125rem] font-bold mb-2">Important Disclaimers</h2>
            <p>
              Stocksist is <strong>NOT</strong> a registered broker-dealer, investment advisor, or financial planner. Nothing on this website constitutes personalized financial advice. All data, analysis, AI-generated insights, and screener results are provided for educational and informational purposes only. You should always consult with a qualified, licensed financial professional before making any investment decisions.
            </p>
            <p className="mt-2">
              Trading stocks, options, and credit spreads involves substantial risk of loss. Past performance is not indicative of future results. Stocksist and its affiliates are not responsible for any financial losses incurred as a result of using data or analysis from this platform.
            </p>
          </section>

          <section>
            <h2 className="text-[1.125rem] font-bold mb-2">Contact Us</h2>
            <p>
              If you have any questions about our affiliate relationships, advertising practices, or editorial policies, please contact us at{" "}
              <a href="mailto:info@stocksist.com" className="text-accent-blue hover:underline">
                info@stocksist.com
              </a>{" "}
              or visit our{" "}
              <a href="/contact" className="text-accent-blue hover:underline">Contact page</a>.
            </p>
          </section>
        </div>
      </div>

      <div className="w-full flex flex-col items-center border-t border-border bg-surface py-1 mt-8">
        <AdBanner slot="bottom" />
      </div>
    </>
  );
}
